language: python

sudo: false

notifications:
  email:
     recipients:
       - nickpapior@gmail.com
     on_failure: always
     on_success: change

python:
  - 2.7
  - 3.4
  - 3.5
    env: COVERAGE=true

matrix:
  include:
   - python: 2.7
     env: PYTHONOPTIMIZE=0
   - python: 2.7
     env: PYTHONOPTIMIZE=1
   - python: 2.7
     env: PYTHONOPTIMIZE=2

install:
  - pip install coverage
  - python setup.py install

script:
  - nosetests --with-coverage --exe sisl

after_success:
  - if [[ ${COVERAGE:-false} != false ]]; then bash <(curl -s https://codecov.io/bash) ; fi


#
# These are setup scripts:
#

addons:
  apt:
    packages: &common_packages
      - gfortran
      - libhdf5-serial-dev 
      - libnetcdf-dev
      # Speedup builds, particularly when USE_CHROOT=1
      - eatmydata

before_install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh ;
    else
        wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh ;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
# Do actual package installations
  - conda info -a
  - echo "nose" >> requirements.txt
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION --file requirements.txt
  - source activate test-environment
